### GetAll 
GET http://localhost:3000/api/users
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlclR5cGUiOiJub3JtYWxfdXNlciIsImlhdCI6MTczNTI3NzU1Nn0.eEtbqwgKcNf9GZl66LsMowANhYsMbk-vBLfnALbCoWc

### GetOne 
GET http://localhost:3000/api/users/2
Content-Type: application/json


### Register
POST  http://localhost:3000/api/users/auth/register
Content-Type: application/json
Authorization:  Bearer 

{
  "username":"hady",
  "email": "hadyhashim17@gmail.com",
  "password": "123456789"
}


### login
POST  http://localhost:3000/api/users/auth/login
Content-Type: application/json
Authorization:  Bearer 

{
  "email": "hadyhashim17@gmail.com",
  "password": "123456789"
}


### gey current user data  
GET  http://localhost:3000/api/users/current-user
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlclR5cGUiOiJub3JtYWxfdXNlciIsImlhdCI6MTczNTI3Mzc5NX0.cB5hkhT3PtR8e6tLxmVWuM_QJR_OJQC1jkq9Lz_IK5o







### DeleteONE 
DELETE  http://localhost:3000/api/users/1
Content-Type: application/json
